README: document KAUI_CONFIG_DAO_ADAPTER property
When using PostgreSQL, one needs to specify `KAUI_CONFIG_DAO_ADAPTER=postgresql` for Kaui.

Otherwise, Kaui fails to start with the following error:

```
org.jruby.rack.RackInitializationException: No such file to load -- java.lang.StackOverflowError: null.rb
```